export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERR = 'LOGIN_ERR';
export const LOGOUT_BEGIN = 'LOGOUT_BEGIN';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERR = 'LOGOUT_ERR';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ALL_CATEGORIES = 'ALL_CATEGORIES';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const CATEGORY_ERR = 'CATEGORY_ERR';
export const CATEGORY_CHK_LIST_INITIALIZE = 'CATEGORY_CHK_LIST_INITIALIZE';
export const CATEGORY_CHK_LIST_CHANGE = 'CATEGORY_CHK_LIST_CHANGE';

export const ADD_CHAIN = 'ADD_CHAIN';
export const ALL_CHAINS = 'ALL_CHAINS';
export const UPDATE_CHAIN = 'UPDATE_CHAIN';
export const DELETE_CHAIN = 'DELETE_CHAIN';
export const CHAIN_ERR = 'CHAIN_ERR';
export const CHAIN_CHK_LIST_INITIALIZE = 'CHAIN_CHK_LIST_INITIALIZE';
export const CHAIN_CHK_LIST_CHANGE = 'CHAIN_CHK_LIST_CHANGE';

export const ADD_USER = 'ADD_USER';
export const ALL_USERS = 'ALL_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const USER_ERR = 'USER_ERR';

export const ADD_NEWS_FEED_SOURCE = 'ADD_NEWS_FEED_SOURCE';
export const ALL_NEWS_FEED_SOURCES = 'ALL_NEWS_FEED_SOURCES';
export const UPDATE_NEWS_FEED_SOURCE = 'UPDATE_NEWS_FEED_SOURCE';
export const DELETE_NEWS_FEED_SOURCE = 'DELETE_NEWS_FEED_SOURCE';
export const NEWS_FEED_SOURCE_ERR = 'NEWS_FEED_SOURCE_ERR';

export const ADD_MEDIA = 'ADD_MEDIA';
export const ALL_MEDIAS = 'ALL_MEDIAS';
export const UPDATE_MEDIA = 'UPDATE_MEDIA';
export const DELETE_MEDIA = 'DELETE_MEDIA';
export const MEDIA_ERR = 'MEDIA_ERR';

export const ADD_PROJECT = 'ADD_PROJECT';
export const ALL_PROJECTS = 'ALL_PROJECTS';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const PROJECT_ERR = 'PROJECT_ERR';
export const SORTING_PROJECT_BY = 'SORTING_PROJECT_BY';
export const SET_PROJECT_ID = 'SET_PROJECT_ID';
export const SET_PROJECT_ACTION = 'SET_PROJECT_ACTION';
export const SET_PROJECT = 'SET_PROJECT';
export const SET_TRENDING_NFTS = 'SET_TRENDING_NFTS';
export const SET_PROJECT_NOT_DB = 'SET_PROJECT_NOT_DB';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';

export const ADD_LIVE_FEED = 'ADD_LIVE_FEED';
export const ALL_LIVE_FEEDS = 'ALL_LIVE_FEEDS';
export const UPDATE_LIVE_FEED = 'UPDATE_LIVE_FEED';
export const DELETE_LIVE_FEED = 'DELETE_LIVE_FEED';
export const LIVE_FEED_ERR = 'LIVE_FEED_ERR';
export const SORTING_LIVE_FEED_BY = 'SORTING_LIVE_FEED_BY';
export const SET_LIVE_FEED_ID = 'SET_LIVE_FEED_ID';
export const SET_LIVE_FEED = 'SET_LIVE_FEED';
export const FILTERING_LIVE_FEED_BY_PROJECT = 'FILTERING_LIVE_FEED_BY_PROJECT';
export const SET_FILTERED_LIVE_FEEDS = 'SET_FILTERED_LIVE_FEEDS';

export const ADD_GUIDE = 'ADD_GUIDE';
export const ALL_GUIDES = 'ALL_GUIDES';
export const UPDATE_GUIDE = 'UPDATE_GUIDE';
export const DELETE_GUIDE = 'DELETE_GUIDE';
export const GUIDE_ERR = 'GUIDE_ERR';
export const SET_GUIDE_ID = 'SET_GUIDE_ID';
export const SET_GUIDE_ACTION = 'SET_GUIDE_ACTION';
export const SET_GUIDE = 'SET_GUIDE';

export const ADD_MEMBER = 'ADD_MEMBER';
export const ALL_MEMBERS = 'ALL_MEMBERS';
export const UPDATE_MEMBER = 'UPDATE_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const MEMBER_ERR = 'MEMBER_ERR';
export const SET_MEMBER_ID = 'SET_MEMBER_ID';
export const SET_MEMBER_ACTION = 'SET_MEMBER_ACTION';
export const SET_MEMBER = 'SET_MEMBER';

export const TOP_SALES = 'TOP_SALES';
export const TOP_SALES_ERR = 'TOP_SALES_ERR';

export const TOP_COLLECTIONS = 'TOP_COLLECTIONS';
export const TOP_COLLECTIONS_ERR = 'TOP_COLLECTIONS_ERR';

export const DAY_SALES = 'DAY_SALES';
export const DAY_SALES_ERR = 'DAY_SALES_ERR';

export const GAINERS_LOOSERS = 'GAINERS_LOOSERS';
export const GAINERS_LOOSERS_ERR = 'GAINERS_LOOSERS_ERR';

export const TRADING = 'TRADING';
export const SET_CURRENT_SLUG = 'SET_CURRENT_SLUG';
export const TRADING_ERR = 'TRADING_ERR';

export const BIGGEST_SALES_AMOUNT = 'BIGGEST_SALES_AMOUNT';
export const BIGGEST_SALES_AMOUNT_ERR = 'BIGGEST_SALES_AMOUNT_ERR';
